receivers:
  otlp/app:
    protocols:
      grpc:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"

  otlp/spanmetrics_output:
    protocols:
      grpc:
        endpoint: "localhost:55677"

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: otel
    metric_expiration: 15m
    # const_labels:
    #   label1: value1
  logging:
    loglevel: warn


  otlp/spanmetrics:
    endpoint: "localhost:55677"
    insecure: true

  # Export for Jaeger
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true




processors:
  batch:

  spanmetrics:
    metrics_exporter: otlp/spanmetrics
    latency_histogram_buckets: [ 0.01s,0.018000000000000002s,0.032400000000000005s,0.05832000000000001s,0.10497600000000003s,0.18895680000000006s,0.34012224000000013s,0.6122200320000003s,1.1019960576000005s,1.983592903680001s, 3.570467226624002s, 6.426841007923204s, 11.568313814261767s, 20.82296486567118s, 37.48133675820813s, 67.46640616477464s, 121.43953109659435s, 218.59115597386983s, 393.4640807529657s, 708.2353453553383 ]
    dimensions:
      - name: http.method
        default: GET
      - name: http.status_code

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp/app]
      processors: [spanmetrics, batch]
      exporters: [logging, jaeger]

    # The exporter name must match the metrics_exporter name.
    # The receiver is just a dummy and never used; added to pass validation requiring at least one receiver in a pipeline.
    metrics/spanmetrics:
      receivers: [otlp/spanmetrics]
      exporters: [otlp/spanmetrics]

    metrics:
        receivers: [otlp/app, otlp/spanmetrics_output]
        processors: [batch]
        exporters: [logging, prometheus]
