scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]

  - job_name: 'app1'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - 'app1'
        type: 'A'
        port: 9000
        refresh_interval: 15s

  - job_name: 'app2'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - 'app2'
        type: 'A'
        port: 9000
        refresh_interval: 15s

  - job_name: 'app3'
    scrape_interval: 10s
    dns_sd_configs:
      - names:
          - 'app3'
        type: 'A'
        port: 9000
        refresh_interval: 15s