scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]

  - job_name: 'app1'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'app1:9000' ]

  - job_name: 'app2'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'app2:9000' ]

  - job_name: 'app3'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'app3:9000' ]
